spring:
  datasource:
    username: admin
    password: strongPassword
    url: jdbc:postgresql://${PACKING_DB_HOST:localhost}:5432/${PACKING_DB:packing_challenge}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true